spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: bandall77!
    hikari:
      data-source-properties:
        rewriteBatchedInserts: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
          batch_size: 100
        show_sql: true
        highlight_sql: true
        order_inserts: true
        order_updates: true
  
  data:
    redis:
      host: localhost
      port: 6379
      password:

jwt:
  header: Authorization
  secret: VG9CU0dPUUFzblNVMVR4bEs2N1daU0hXUnJKQ0ZhSG4yYWVoSUdMZmZiTVY5YXBmUHNCcGVUNHlZSTFWVVVTOA==

verification:
  encoder-strength: 4
  email:
    expire-time: 3600
    do-email-verification: false

navigation:
  api:
    naver:
      url: https://naveropenapi.apigw.ntruss.com/map-direction/v1/driving?start=%s&goal=%s&option=%s
      client-id: g33oc99jt8
      api-key: 61HJeITzsZxPH8DuE4dHOt8xgFuoxmJiDmA5yawE
    osrm:
      driving-url: http://127.0.0.1:5000/route/v1/driving/%s;%s?steps=%s&overview=full&geometries=geojson
      table-url: http://127.0.0.1:5000/table/v1/driving/%s?sources=%s&destinations=%s&annotations=duration,distance



logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%mdc{traceId}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
