spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: bandall77!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  port: 8000
  error:
    include-message: never

jwt:
  header: Authorization
  secret: VG9CU0dPUUFzblNVMVR4bEs2N1daU0hXUnJKQ0ZhSG4yYWVoSUdMZmZiTVY5YXBmUHNCcGVUNHlZSTFWVVVTOA==

verification:
  encoder-strength: 4

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%mdc{traceId}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
